### ISSUE TITLE
Temperature reading anomaly [possibly the app does not work with G15 5510]

### ISSUE THREAD

**Issue by mojujul** [AlexIII/tcc-g15#12]
The app cannot correctly read the temperature of the stand-alone game graphics card on the G15 5510. At any time, the GPU temperature displayed on the application interface will not exceed 35 ° C

**Comment by AlexIII** [comment]
Hi!
Thanks for your report.
5510 is not currently in the list of supported models. If you wish to investigate the problem further, give some details and/or provide code, we can include your fix in the app.
I only have 5515, so cannot test anything else myself.

**Comment by AlexIII** [comment]
It very well may be. I use Dell driver under the hood to read the temperature, so it will be (should be) identical to what AWCC shows. It it too shows the wrong value, I'm afraid this problem is out of my depth.

**Comment by MegatronQAQ** [comment]
Hello, the temperature displayed by msi afterburner and HWINFO is normal, is there a way for you to use their interface? HWINFO seems to be able to call data if it is not used for profit.
