### ISSUE TITLE
Enable/Disable autorun buttons causes the app to close when it's minimized

### ISSUE THREAD

**Issue by chz2333** [AlexIII/tcc-g15#13]
将程序页面最小化之后，在托盘的小图标开关开机自启动会让程序关闭

**Comment by AlexIII** [comment]
I don't understand. What's the problem?

**Comment by AlexIII** [comment]
Oh, I think I got it. You're right, there's something weird is going on.

**Comment by chz2333** [comment]
> Oh, I think I got it. You're right, there's something weird is going on.

Turning on enabling autorun doesn't seem to work😣

**Comment by AlexIII** [comment]
Fixed in [1.5.1](https://github.com/AlexIII/tcc-g15/releases). Please give it a try!

**Comment by chz2333** [comment]
> Please give it a try!

👍
