### ISSUE TITLE
G mode 

### ISSUE THREAD

**Issue by ADEFEIZHAI** [AlexIII/tcc-g15#15]
Hello, thank you for developing this tool, I am currently got a problem with my G15 5520 where the tool automatically turns on G mode as soon as I switch on the laptop. 
As well as not reaching the set temperature it also inexplicably turns on G mode. I wonder if there is a solution for this.

**Comment by AlexIII** [comment]
Hi! Try unchecking "Fail-safe" checkbox in the UI

**Comment by ADEFEIZHAI** [comment]
I reinstalled and rebooted many times and now the problem seems to be solved.
