### ISSUE TITLE
Wrong GPU Thermal Display (Dell G15 5511)

### ISSUE THREAD

**Issue by ItsukaHiro** [AlexIII/tcc-g15#17]
Because most of the time, my GPU run at 30 degree, constantly. So I decide to check in Task Manager and HWMonitor.

Compare to Task Manager:
![image](https://github.com/AlexIII/tcc-g15/assets/64533662/fe7de9d3-8649-4ffd-bed5-610e40bd53ff)

Compare to HWMonitor:
![image](https://github.com/AlexIII/tcc-g15/assets/64533662/a3e35e4b-c635-4e5c-9c73-b767e2de8277)

IDK but when HWMonitor started, the TCC's GPU thermal instantly jump from 30 degree to 43 degree, matched to HWMonitor's one.

Bonus: Sometimes it jump back to accurate thermal, but comeback in around 30s ~ 1m (not in using HWMonitor-case).

**Comment by AlexIII** [comment]
Thanks for the report! Not sure what to say. My app is just an UI over the Dell wmi interface. WMI provides the actual number for the temperature. Other apps probably use different APIs. The only thing that this app numbers should be consistent to is the official Dell AWCC app.
