### ISSUE TITLE
something wrong when using tcc-g15

### ISSUE THREAD

**Issue by CY-HE** [AlexIII/tcc-g15#20]
![1710154376359](https://github.com/AlexIII/tcc-g15/assets/162985734/155761fd-d6d6-4bc0-8229-85864b2b8523)

**Comment by AlexIII** [comment]
Seems like a problem with the COM service in the system. Sorry, don't know what this error mean exactly.

**Comment by Grapeeeee** [comment]
Check out that the **windows management instrumentation** service is starting normally？
