### ISSUE TITLE
Rebooting the system will restore the hardware temperature presets.

### ISSUE THREAD

**Issue by Sunsetheart3939** [AlexIII/tcc-g15#24]
The windows system boot or reboot causes the settings for threshold GPU Temp and threshold CPU Temp to default to 30 and 30. Is it necessary to manually re-edit every time, or is it possible to save personal settings?

**Comment by AlexIII** [comment]
Hi!
What you're experiencing is not normal... Not only the settings should be saved between reboots, the default values for GPU and CPU are 85 and 95 respectively, not 30.
The settings are stored in the registry, you can check the current saved temp thresholds by navigating to `\HKEY_CURRENT_USER\Software\github.com/AlexIII/tcc-g15\AWCC\app\fan\cpu`
![image](https://github.com/AlexIII/tcc-g15/assets/10047074/05796078-5303-4f32-b7fc-df492e5d20bb)

Also, try closing the app and deleting "github.com/AlexIII/tcc-g15" folder in the registry, this should reset the settings to default.
