### ISSUE TITLE
SWbemObjectEx error

### ISSUE THREAD

**Issue by phantomfancy** [AlexIII/tcc-g15#25]
![error](https://github.com/AlexIII/tcc-g15/assets/89564432/cb7ad8cd-b606-487e-b18e-ff5a00fec597)

After installation, I encountered two errors,and couldn't use tcc.
pywintypes.com_error: (-2147352567, '发生意外。', (0, 'SWbemObjectEx', '常规故障 ', None, 0, -2147217407), None)
wmi.x_wmi: <x_wmi: Unexpected COM Error (-2147352567, '发生意外。', (0, 'SWbemObjectEx', '常规故障 ', None, 0, -2147217407), None)>

**Comment by AlexIII** [comment]
Hi! Please check you have the original drivers for awcc installed. You can remove only some of awcc components, but not the driver.
