### ISSUE TITLE
How to modify default settings

### ISSUE THREAD

**Issue by Xtian-hfuu** [AlexIII/tcc-g15#28]
First ,thank you very much for this software.This application is very good and useful.

My computer is G3 3590,this software can also run perfectly.But every time the device is turned on, it needs to be manually adjusted to a custom setting and the temperature threshold also needs to be reset.

May I ask if this software supports modifying default configurations? If supported, what should I do？

**Comment by AlexIII** [comment]
Hi! The app should save the settings between restarts automatically.
Please see if suggestions from #24 will help.

**Comment by Xtian-hfuu** [comment]
![{DA487CC7-A0D5-4bfb-9858-94F1FEB6F0D9}](https://github.com/AlexIII/tcc-g15/assets/106716242/69482f7a-7a54-4218-b960-3119ba3b2d07)
Thank you for your advice,but it doesn't seem to work on my computer.I don't have these fan value in my registry.
Maybe because my computer is G3 not G15?

**Comment by AlexIII** [comment]
I think the app don't have enough system permissions to save the settings. Maybe you have some non-default security policies or something like that. Hard to guess.

**Comment by Xtian-hfuu** [comment]
Okay.Anyway, thank you for you suggesion.This is also a small problem,if it cannot be solved, it will not affect daily use.
