### ISSUE TITLE
Set the default mode for autostart

### ISSUE THREAD

**Issue by SoongSH** [AlexIII/tcc-g15#29]
Many users have encountered the same problem. The program always defaults to G mode after startup. Can it remember the last selection and execute it?

**Comment by AlexIII** [comment]
Hi!
Try selecting 'Balanced' mode, then right click the tray icon and select 'Exit'. The next time you ran the app it should restore the mode (and all other settings).

**Comment by SoongSH** [comment]
Hi!
Thank you!

Alexander Blk ***@***.***> 于2024年6月15日周六 15:35写道：
