### ISSUE TITLE
what's the use of the two numbers on the bottom right

### ISSUE THREAD

**Issue by niwojing** [AlexIII/tcc-g15#31]
the numbers are in the middle of failsafe and the green pot,and can this program changes fan speed autolly when i play games?sorry for my poor english hhh

**Comment by AlexIII** [comment]
You can get description of the fields if you hover over them with the mouse pointer for 2 seconds
![image](https://github.com/AlexIII/tcc-g15/assets/10047074/6c0040f7-74ca-4e90-a497-c87ab694eb25)

The green dot shows if the failsafe triggered or not (green - not triggered, red - triggered, yellow - triggered in the past)

**Comment by niwojing** [comment]
i got it，thanks for your reply.
