### ISSUE TITLE
About Fan Speed

### ISSUE THREAD

**Issue by Kagura-Nanaa** [AlexIII/tcc-g15#36]
I've noticed that even in custmon mode with the fan set to max speed it's still slower than the g mod, is this a bug? Is it possible to set it to max speed in custmon mode?

**Comment by AlexIII** [comment]
Hi!
Please read [Limitations](https://github.com/AlexIII/tcc-g15?tab=readme-ov-file#limitations) section in readme.

> Manual fan contoll is not really manual. If you set fan speed too low the BIOS will takeover and raise the fan speed automatically when the GPU/CPU temperature reaches certain point to prevent overheating.

This is the case for both maximum and minimum speeds. The internal firmware doesn't take seriously the speed that is set by the user and only follows it loosely.
