### ISSUE TITLE
runs well on G3 3590！and may I ask if you can adapt the G key

### ISSUE THREAD

**Issue by SunshineboyZj** [AlexIII/tcc-g15#39]
This software is compatible with Dell G3 3590 and runs well on my computer. The temperature display, speed display, balance mode, G mode (maximum fan speed), and manual speed adjustment mode can all work normally
Also, may I ask if you can adapt the G key (to facilitate quick switching between balanced mode and G mode (maximum fan speed))
Also, thank you very much for developing the software (the official AWCC is really difficult to use!)

**Comment by SunshineboyZj** [comment]
Also, thank you very much for developing the software (the official AWCC is really difficult to use!)

**Comment by swy4four** [comment]
v1.6 can adapt the G key

**Comment by AlexIII** [comment]
Thanks for the feedback!
As was mentioned above, G-key support was added in the recent 1.6.0 release. Do check it out!
