### ISSUE TITLE
Unlocking Fan Speed Limit

### ISSUE THREAD

**Issue by Babubaztc** [AlexIII/tcc-g15#41]
Hello developers, thank you very much for developing such a small and compact open source software, here I would like to give you some feedback. As you know I'm also a Dell G15 laptop user, my model is 5511, but I've noticed that there seems to be an upper limit to the speed of my laptop fan during normal use: for example, my GPU\CPU fan rotates around 4700/4400 during daily use if I set it to G mode or manually push the fan speed to the maximum, but I've noticed that the laptop fan has a significantly higher speed when I update the BIOS version ——the laptop fan had a noticeably higher RPM (probably over 5000RPM or even close to 6000RPM) because I heard a sharper airflow. Apparently my fan speed is limited in some way, and the full speed of the fan can only be turned on under certain circumstances. And as users of the G15, we agree that its cooling module design is flawed and it will always have issues with overheating and downclocking, etc., so I'm wondering if you can somehow lift the fan speed limitation that could allow for better cooling performance of this model of laptop.

**Comment by AlexIII** [comment]
Hi! Unfortunately I don't know if there's a controllable fan speed limit exists, but what I can say is that even with the API Dell provides the fan speed that user requests is just a 'suggestion' to the system, the actual speed is determined by some unknown internal algorithm in the firmware. So it's not surprising at all to get speeds that differ from other laptop models/units.

**Comment by Babubaztc** [comment]
﻿﻿Greetings! I was very surprised that you were able to respond so quickly. I think I understand what you mean, maybe controlling the fan speed is determined by deeper firmware and microcode, I decided not to think about it anymore. But anyway thank you very much for the open source software and the patient and detailed reply.在 2024年9月6日，20:14，Alexander Blk ***@***.***> 写道：﻿
Hi! Unfortunately I don't know if there's a controllable fan speed limit exists, but what I can say is that even with the API Dell provides the fan speed that user requests is just a 'suggestion' to the system, the actual speed is determined by some unknown internal algorithm in the firmware. So it's not surprising at all to get speeds that differ from other laptop models/units.
