### ISSUE TITLE
It works on the G15 5535

### ISSUE THREAD

**Issue by Dhia-zorai** [AlexIII/tcc-g15#42]
I've struggled with AWCC,it wouldn't even launch after a week of buying this laptop,so if you are in my boat i highly recommend to download this instead.

Although like most users i would apreciate the G hotkey,and maybe some presets for battery life like in AWCC, because i really dont want to manually experiment on my laptop or push it to its limits.

And thank you for this app.

**Comment by AlexIII** [comment]
Many thanks for your feedback!
Support for G hotkey is cumming next release, we're currently working on it.
