### ISSUE TITLE
G key

### ISSUE THREAD

**Issue by GsonLi** [AlexIII/tcc-g15#43]
V1.6 will return to balanced mode instead of custom mode every time when G mode is cancelled through the G key.

**Comment by AlexIII** [comment]
Hi! The intended behavior is that after disabling G-mode with the G-key the app returns to the mode that was set before G-key was pressed the first time. Example:

current mode: balanced -> pressing G-key, mode: g-mode ->  pressing G-key, mode: balanced

current mode: custom -> pressing G-key, mode: g-mode ->  pressing G-key, mode: custom

**Comment by GsonLi** [comment]
Hi, I tried to reproduce this issue again, but I found that the switch is ok. Maybe I made a mistake. Anyway, thank you!
