### ISSUE TITLE
谢谢大佬 戴尔G3 3590 可以用

### ISSUE THREAD

**Issue by Tomori77** [AlexIII/tcc-g15#45]
当前日期/时间：2024年10月2日，18:13：24
操作系统：Windows10专业版64位（10.0，版本18363）
系统型号：G33590
BIOS: 1.11.1
处理器：Intel（R)Core（TM）i7-9750H CPU @2.60GHz（12 CPUs）,~2.6GHz
内存：16384MBRAM

我是可以用的，希望新来的兄弟们也可以用，如果有G3的兄弟运气好找到了这，直接下载开冲吧

**Comment by AlexIII** [comment]
Thank you for the feedback!
