### ISSUE TITLE
wrong GPU model displayed

### ISSUE THREAD

**Issue by Terryxtl** [AlexIII/tcc-g15#47]
![{187445B4-C434-43B3-BF73-15B23B034722}](https://github.com/user-attachments/assets/0d1ae269-2a8c-44e7-a263-57e69e77701d)
My actual physical gpu is 3060laptop
but the name of a virtual driver for rdp is displayed

**Comment by AlexIII** [comment]
Thank you for the report! Would you be able/willing to test a fix? (If you have local python installed)

**Comment by Terryxtl** [comment]
Sure

**Comment by Terryxtl** [comment]
![{F2071A48-0C27-4E1B-A430-D6CB8CE6E09F}](https://github.com/user-attachments/assets/2d889dd7-dd2b-4b8e-84c1-adf77dd75148)
nicely fixed!

**Comment by AlexIII** [comment]
I was just writing the instruction, but it seems you've already figured it all out! Is it from `fix1` branch?

**Comment by Terryxtl** [comment]
yes

**Comment by AlexIII** [comment]
Alright, thank you! I will do a proper release in a moment.
