### ISSUE TITLE
I wonder if it can work on g15 5520

### ISSUE THREAD

**Issue by misakayuuki** [AlexIII/tcc-g15#5]
will it support g15 5520?

**Comment by AlexIII** [comment]
Hi! I don't know, I own only 5515. But do try it. Worst case scenario it just won't work. The program does not make any permanent changes to the system.
Really appreciate if you would report back with your results.

**Comment by THSLP13** [comment]
From far future...
It perfectly supports G15 5520.Either G Mode or manual fan speed control.

**Comment by AlexIII** [comment]
Thank you for letting me know! I will add 5520 to the documentation.
