### ISSUE TITLE
A Small Suggestion: Add a Marker to the System Tray Icon to Indicate Whether "G Mode" is Enabled or Not

### ISSUE THREAD

**Issue by kailun1107** [AlexIII/tcc-g15#51]
Have you ever considered adding some sort of indicator to the system tray icon to show whether the "G Mode" is currently enabled? Although I can judge by listening to the sound of the fan, sometimes when I'm wearing headphones and deeply concentrated on gaming, it would be more convenient if I could determine it directly from the icon.

Regardless, this is just a small suggestion. Thank you for your hard work, it has been very helpful to me.

**Comment by AlexIII** [comment]
Hi! Good suggestion! will take into consideration. Thank you.

**Comment by AlexIII** [comment]
Addressed in `1.6.3`. 
https://github.com/AlexIII/tcc-g15?tab=readme-ov-file#ui-hints
