### ISSUE TITLE
fail-safe  setting

### ISSUE THREAD

**Issue by uNnoWnF** [AlexIII/tcc-g15#56]
Hello！Your software is great！

I have a little problem.

Every time I start up the computer, the fail-safe option is always set to on by default. How can I make this option default to off?

Thank you

**Comment by AlexIII** [comment]
Hi! What app version do you use? Please update to the latest version, previous versions had this problem, but it was fixed.
Let me know if the update doesn't fix it for you.

**Comment by uNnoWnF** [comment]
It works！The new version is awsome

love it
