### ISSUE TITLE
Limit the program to have no more than one instance in the system

### ISSUE THREAD

**Issue by babyNEKO** [AlexIII/tcc-g15#8]
能否限制只能运行一个 😉
![屏幕截图 2023-07-09 145854](https://github.com/AlexIII/tcc-g15/assets/34335425/18e6cae1-5cf9-4823-8af5-0d3281338479)

**Comment by AlexIII** [comment]
Yes, thanks for the report! We'll need to address this.

**Comment by babyNEKO** [comment]
Thanks
